# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.
#
# See /usr/share/doc/unbound/examples/unbound.conf for a commented
# reference config file.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"

# Версия: 1.0 (22.03.2026)
# Ответственный: P1

server:

    # ── СЕТЕВОЙ ИНТЕРФЕЙС ──────────────────────────────────────────
    interface: 0.0.0.0
    port: 53

    # ── УПРАВЛЕНИЕ ДОСТУПОМ ────────────────────────────────────────
    access-control: 0.0.0.0/0 refuse
    access-control: 127.0.0.0/8 allow
    access-control: 10.10.0.0/24 allow # думаю тут подразумевается наша сетка

    # ── ПРОТОКОЛЫ ──────────────────────────────────────────────────
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    # ── ЛОГИРОВАНИЕ ────────────────────────────────────────────────
    verbosity: 3
    logfile: ""
    use-syslog: no # docker logs
    log-queries: yes
    log-replies: yes
    log-tag-queryreply: yes

    # ── ПРОИЗВОДИТЕЛЬНОСТЬ ─────────────────────────────────────────
    num-threads: 2
    msg-cache-size: 64m
    rrset-cache-size: 128m
    neg-cache-size: 16m
    so-rcvbuf: 4m

    # ── ПОВЕДЕНИЕ РЕЗОЛВЕРА ────────────────────────────────────────
    do-not-query-localhost: no
    hide-identity: yes
    hide-version: yes
    harden-glue: yes
    harden-dnssec-stripped: yes

    # ── КОРНЕВЫЕ ПОДСКАЗКИ ─────────────────────────────────────────
    root-hints: "" # /etc/unbound/root.hints

    # ── DNSSEC ─────────────────────────────────────────────────────
    auto-trust-anchor-file: "" # /var/lib/unbound/root.key

    # ── МОДУЛИ (порядок важен!) ────────────────────────────────────
    module-config: "validator iterator"

    # ── PREFETCH ───────────────────────────────────────────────────
    prefetch: yes # обновлять кэш когда TTL < 10% от исходного
    prefetch-key: yes # также обновлять DNSSEC-ключи заблаговременно
    minimal-responses: no # не включаем, нужны полные ответы для логов

    # ── УПРАВЛЕНИЕ TTL ───────────────────────────────────────────────────
    cache-min-ttl: 330      # Минимум 5.5 минут
    cache-max-ttl: 82800    # Максимум 23 часа
    cache-max-negative-ttl: 3600 # для ошибок (NXDOMAIN и NODATA)

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 8953

